In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Segment 3: Matrix Properties

# Frobenius Norm

In [3]:
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [5]:
# mannual
(1**2 + 2**2 + 3**2 + 4**2) ** (1/2)

5.477225575051661

In [4]:
# numpy 
np.linalg.norm(X) # same function as for vector L2 norm

5.477225575051661

# Matrix Multiplication (with a Vector)


In [3]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [4]:
b = np.array([1, 2])
b

array([1, 2])

In [5]:
np.dot(A, b) # even though technically dot products are between vectors only

array([11, 17, 23])

### Matrix Multiplication (with Two Matrices)

In [6]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [7]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [8]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

Note that matrix multiplication is not "commutative" (i.e., AB not equal to BA 
) so uncommenting the following line will throw a size mismatch error:

In [10]:
#np.dot(B, A)

# Symmetric Matrices

In [12]:
X_sym = np.array([[0,1,2], [1,7,8], [2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [13]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [14]:
# check the condition
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Matrix Inversion


In [15]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [16]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [18]:
y = np.array([4, -7])
y

array([ 4, -7])

In [19]:
w = np.dot(Xinv, y)
w

array([-1.,  4.])

In [20]:
np.dot(X, w)

array([ 4., -7.])

# Matrix Inversion Where No Solution


In [21]:
X = np.array([[-4, 1], [-8, 2]])
X

array([[-4,  1],
       [-8,  2]])

In [22]:
# Uncommenting the following line results in a "singular matrix" error
Xinv = np.linalg.inv(X)

LinAlgError: Singular matrix

Feel free to try inverting a non-square matrix; this will throw an error too.

# Orthogonal Matrices
These are the solutions to Exercises 3 and 4 on orthogonal matrices from the slides.

For Exercise 3, to demonstrate the matrix I3 has mutually orthogonal columns, we show that the dot product of any pair of columns is zero:

In [23]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
column_1 = I[:,0]
column_1

array([1, 0, 0])

In [25]:
column_2 = I[:,1]
column_2

array([0, 1, 0])

In [26]:
column_3 = I[:,2]
column_3

array([0, 0, 1])

In [28]:
np.dot(column_1, column_2)


0

In [29]:
np.dot(column_1, column_3)

0

In [30]:
np.dot(column_2, column_3)

0

We can use the np.linalg.norm() method from earlier in the notebook to demonstrate that each column of 
 has unit norm:

In [31]:
np.linalg.norm(column_1)
np.linalg.norm(column_2)
np.linalg.norm(column_3)

1.0

Since the matrix I3 has mutually orthogonal columns and each column has unit norm, the column vectors of I3 are orthonormal. Since I3 transposes = I3, this means that the rows of I3 must also be orthonormal.

Since the columns and rows of I3 are orthonormal, I3 is an orthogonal matrix.

For Exercise 4, let's repeat the steps of Exercise 3 with matrix K instead of I3. We could use NumPy again, but for fun I'll use PyTorch instead. (You're welcome to try it with TensorFlow if you feel so inclined.)